services:
  - type: web
    name: community-wallet-frontend
    env: node
    plan: free
    buildCommand: |
      bun install --frozen-lockfile
      bun run build:frontend
    startCommand: cd apps/frontend && bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false

  - type: web
    name: community-wallet-backend
    env: node
    plan: free
    buildCommand: |
      bun install --frozen-lockfile
      bun run build:backend
    startCommand: cd apps/backend && bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: STELLAR_NETWORK
        value: testnet
      - key: BLEND_POOL_ADDRESS
        value: CCLBPEYS3XFK65MYYXSBMOGKUI4ODN5S7SUZBGD7NALUQF64QILLX5B5
