services:
  - type: web
    name: community-wallet-frontend
    env: node
    plan: free
    buildCommand: |
      export SHARP_IGNORE_GLOBAL_LIBVIPS=1
      export SHARP_FORCE_GLOBAL_LIBVIPS=false
      export NODE_ENV=production
      npm install --production=false
      cd apps/frontend && npm install --production=false && npm run build
    startCommand: cd apps/frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: SHARP_FORCE_GLOBAL_LIBVIPS
        value: "false"
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false

  - type: web
    name: community-wallet-backend
    env: node
    plan: free
    buildCommand: |
      export SHARP_IGNORE_GLOBAL_LIBVIPS=1
      export SHARP_FORCE_GLOBAL_LIBVIPS=false
      export NODE_ENV=production
      npm install --production=false
      cd apps/backend && npm install --production=false && npm run build
      ls -la apps/backend/dist/
    startCommand: cd apps/backend && pwd && ls -la dist/ && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SHARP_IGNORE_GLOBAL_LIBVIPS
        value: "1"
      - key: SHARP_FORCE_GLOBAL_LIBVIPS
        value: "false"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STELLAR_NETWORK
        value: testnet
      - key: BLEND_POOL_ADDRESS
        value: CCLBPEYS3XFK65MYYXSBMOGKUI4ODN5S7SUZBGD7NALUQF64QILLX5B5
