[package]
name = "community_wallet"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
blend-contract-sdk = "1.22.0"

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
